// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {
  static Future<Api> getApi() => RustLib.instance.api.crateApiApiApiGetApi();

  Stream<List<String>> getAvailableKeys();

  Stream<List<TimeStampedValue>> getTimestampedSeries({required String key});

  Future<void> loadCsv({required String csvPath});

  Future<void> loadTest();
}
