// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

Future<ArcEngine> loadCsv({required String csvPath}) =>
    RustLib.instance.api.crateApiApiLoadCsv(csvPath: csvPath);

Future<ArcEngine> loadNone() => RustLib.instance.api.crateApiApiLoadNone();

Future<ArcEngine> loadTest() => RustLib.instance.api.crateApiApiLoadTest();

Stream<List<String>> getAvailableKeys({required ArcEngine engine}) =>
    RustLib.instance.api.crateApiApiGetAvailableKeys(engine: engine);

Stream<List<TimeStampedValue>> getTimestampedSeries({
  required ArcEngine engine,
  required String key,
}) => RustLib.instance.api.crateApiApiGetTimestampedSeries(
  engine: engine,
  key: key,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < RwLock < Engine > >>>
abstract class ArcEngine implements RustOpaqueInterface {}
