// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<List<Point>> getTestData() =>
    RustLib.instance.api.crateApiSimpleGetTestData();

class Point {
  final double t;
  final double v;

  const Point({required this.t, required this.v});

  @override
  int get hashCode => t.hashCode ^ v.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          v == other.v;
}
