// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

class TimeStampedValue {
  final double time;
  final double value;

  const TimeStampedValue({required this.time, required this.value});

  @override
  int get hashCode => time.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeStampedValue &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          value == other.value;
}
